# Generated by Django 5.1.4 on 2024-12-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=255, verbose_name='Cédula')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('phone', models.CharField(max_length=255, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('method_payment', models.CharField(choices=[('1', 'Anual'), ('2', 'Semestral')], max_length=255, verbose_name='Forma de Pago')),
                ('holder', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=255, verbose_name='¿El Plan es para el Titular?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_document', models.CharField(max_length=255, verbose_name='Cédula')),
                ('beneficiary_name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('beneficiary_last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('beneficiary_birth_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('beneficiary_phone', models.CharField(max_length=255, verbose_name='Teléfono')),
                ('beneficiary_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('beneficiary_relationship', models.CharField(max_length=255, verbose_name='Parentesco con el Titular')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mail')),
            ],
        ),
    ]
