# Generated by Django 5.1.4 on 2024-12-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='beneficiary_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico(Opcional)'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='beneficiary_last_name',
            field=models.CharField(max_length=255, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='beneficiary_name',
            field=models.CharField(max_length=255, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='beneficiary_phone',
            field=models.CharField(max_length=255, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico(Opcional)'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Celular'),
        ),
    ]
